@startuml

title <b>On The Spot Courier Services</b>\n<b>Domain Model Class Diagram</b>

class Package {
    packageID
    invoiceID
    routeID
    weight
    size
    deliveryType
    priority
    status
    timeAndDateOfOrder
    dropOffContactName
    dropOffContactNumber
}

class Route {
    routeID
    pickUpDriverID
    dropOffDriverID
    pickUpTime
    dropOffTime
    warehousePickUpTime
    warehouseDropOffTime
}

class Invoice {
    invoiceID
    customerID
    amountDue
    dueDate
    paymentDate
    paymentAmount
}

class MonthlyInvoice {
    cycleStart
    cycleEnd
    paymentDate
}

class IndividualInvoice {
    invoiceDate
}

class Driver {
    driverID
    phoneNumber
    name
}

class Customer {
    customerID
    address
    primaryContact
    phoneNumber
    paymentInformation
}

class IndividualCustomer {
    paymentType
}

class MonthlyCustomer {
    lastInvoice
    lastPayment
    outstandingBalance
}

Invoice<|-IndividualInvoice
Invoice<|--MonthlyInvoice
Customer<|--IndividualCustomer
Customer<|--MonthlyCustomer
IndividualInvoice"0..*"--"1"IndividualCustomer
IndividualInvoice"1"--"1"Package
MonthlyInvoice"0..*"-"1"MonthlyCustomer
MonthlyInvoice"1"--"0..*"Package
Route"0..*"-"1..2"Driver
Route"1"-"1..*"Package

hide methods

@enduml